["臺北市區監理所（含金門馬祖）"]
name = "臺北市區監理所（含金門馬祖）"
   ["臺北市區監理所（含金門馬祖）"."士林監理站(臺北市士林區承德路5段80號)"]
    Station = "士林監理站(臺北市士林區承德路5段80號)"
    First = ["本場次為初考生，請先完成體檢"]
    Retake = ["本場次為重考、吊註銷、持輕機駕照或完成講習之考生(初考生勿預約本場次)"]

   ["臺北市區監理所（含金門馬祖）"."基隆監理站(基隆市七堵區實踐路296號)"]
    Station = "基隆監理站(基隆市七堵區實踐路296號)"
    First = ["本場次為初考生，請先完成體檢"]
    Retake = ["本場次為重考、吊註銷、持輕機駕照或完成講習之考生(初考生勿預約本場次)"]

   ["臺北市區監理所（含金門馬祖）"."金門監理站(金門縣金湖鎮黃海路六之一號)"]
    Station = "金門監理站(金門縣金湖鎮黃海路六之一號)"
    First = ["初考領者"]
    Retake = ["初考領者"]


["臺北區監理所（北宜花）"]
name = "臺北區監理所（北宜花）"
   ["臺北區監理所（北宜花）"."臺北區監理所(新北市樹林區中正路248巷7號)"]
    Station = "臺北區監理所(新北市樹林區中正路248巷7號)"
    First = ["初考領及持有汽車駕照初考機車者", "請先完成體檢"]
    Retake = ["本場次為重考生", "重考生", "吊註銷重考", "持輕機駕照"]

  ["臺北區監理所（北宜花）"."板橋監理站(新北市中和區中山路三段116號)"]
    Station = "板橋監理站(新北市中和區中山路三段116號)"
    First = ["初考生，請先完成體檢"]
    Retake = ["(初考生勿預約本場次)", "重考、吊註銷、持輕機駕照或完成講習"]

  ["臺北區監理所（北宜花）"."宜蘭監理站(宜蘭縣五結鄉中正路二段9號)"]
    Station = "宜蘭監理站(宜蘭縣五結鄉中正路二段9號)"
    First = ["初次報考機車駕照(含輕機)之考生，請先完成體檢"]
    Retake = ["重考生或持輕機駕照或吊註銷重考或完成機車初考領講習之考生"]

  ["臺北區監理所（北宜花）"."花蓮監理站(花蓮縣吉安鄉中正路二段152號)"]
    Station = "花蓮監理站(花蓮縣吉安鄉中正路二段152號)"
    First = ["本場次為初次報考機車(含輕型)駕照之考生"]
    Retake = ["本場次專供重考生、已持有輕型機車駕照、吊註銷重考、已完成機車安全講習之考生"]

  ["臺北區監理所（北宜花）"."玉里監理分站(花蓮縣玉里鎮中華路427號)"]
    Station = "玉里監理分站(花蓮縣玉里鎮中華路427號)"
    First = ["初次考領考生"]
    Retake = ["初次考領考生"]

  ["臺北區監理所（北宜花）"."蘆洲監理站(新北市蘆洲區中山二路163號)"]
    Station = "蘆洲監理站(新北市蘆洲區中山二路163號)"
    First = ["本場次為初考"]
    Retake = ["本場次為重考、吊註銷、持輕機駕照或完成講習"]


# ["監理所名稱"]
    # ["監理所名稱.監理站名稱"]
            # Station = "監理站名稱"
            # First = ["初考關鍵字", "初考關鍵字"]
            # Retake = ["重考關鍵字", "重考關鍵字"]